version: '3.8'

volumes:
  db_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: smalex02/foodgram_project_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_value:/backend_static/
      - media_value:/media

  frontend:
    image: smalex02/foodgram_project_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  gateway:
    image: smalex02/foodgram_project_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/staticfiles/
      - media_value:/media
    depends_on:
      - db