version: '3.3'

volumes:
  db_data:
  static_value:
  media_value:

services:

  db:
    image: postgres:13.10
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: smalex02/foodgram_backend:latest
    volumes:
      - static_value:/backend_static/
      - media_value:/media
    env_file: .env
    depends_on:
      - db

  frontend:
    image: smalex02/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    build: ./infra/
    ports:
      - 8000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/staticfiles/
      - media_value:/media
    depends_on:
      - backend
